### ISSUE TITLE
[BUG] No Longer Works with PLUGIN MANGER

### ISSUE THREAD

**Issue by winkerbie** [LFriede/x64dbg-updater#2]
The updater no longer works with the plugin manager.

Whilst the updater correctly recognises a new build it sends the wrong command to the plugin manager. 
It should be: `x64plgmnrc.exe -i x64core` rather than `--updateall`

**Comment by LFriede** [comment]
Old plugin manager versions compared only the "tag" of github releases, the tag of x64dbg is "snapshot" everytime so the plugin manager never updated it. The new 0.5 version of plugin manager fixes this behaviour, so now everything should be working as expected.
